name: Tokate
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, reopened, synchronize, edited, ready_for_review, converted_to_draft, labeled, unlabeled, assigned, unassigned]
permissions: {}
jobs:
  coordinate:
    permissions:
      contents: write
      issues: read
      pull-requests: write
    uses: obselate/tokate/.github/workflows/tokate-shared.yml@95f3b8b8eae82ce54ec9adc7482ffa4601fa4834
    with:
      archive_url: 'https://api.github.com/repos/obselate/tokate/releases/assets/621931367'
      archive_sha256: '074a51f9641dc2fb3af7e2ee2f284e5a96c728693166da32b54e739081e21812'
      member: 'tokate-0.2.95-linux-x64/tokate'
